using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace FarmSlice.EditorTools
{
    // Builds the playable "FarmSlice" scene from Assets/FarmSlice/farm_slice_map.json
    // (generated by the map pipeline). Menu: Farm Slice > Build Farm Slice Scene.
    public static class FarmSliceSceneBuilder
    {
        const string MapPath = "Assets/FarmSlice/farm_slice_map.json";
        const string ScenePath = "Assets/FarmSlice/Scenes/FarmSlice.unity";

        [MenuItem("Farm Slice/Build Farm Slice Scene")]
        public static void Build()
        {
            var json = File.ReadAllText(MapPath);
            var map = JsonUtility.FromJson<MapData>(json);

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var mats = map.materials.ToDictionary(
                m => m.key,
                m => AssetDatabase.LoadAssetAtPath<TileBase>(m.path));

            var gridGo = new GameObject("Grid");
            var grid = gridGo.AddComponent<Grid>();
            grid.cellSize = new Vector3(1f, 1f, 0f);

            Tilemap Layer(string name, int order)
            {
                var go = new GameObject(name);
                go.transform.SetParent(gridGo.transform, false);
                var tm = go.AddComponent<Tilemap>();
                var r = go.AddComponent<TilemapRenderer>();
                r.sortingOrder = order;
                return tm;
            }

            var ground = Layer("Ground", 0);
            var soil = Layer("Soil", 1);
            var path = Layer("Path", 2);
            var water = Layer("Water", 3);
            var decor = Layer("Decor", 4);

            Fill(ground, map.ground, mats);
            Fill(soil, map.soil, mats);
            Fill(path, map.path, mats);
            Fill(water, map.water, mats);

            foreach (var c in map.decor)
            {
                var tile = AssetDatabase.LoadAssetAtPath<TileBase>(c.m);
                if (tile) decor.SetTile(new Vector3Int(c.x, c.y, 0), tile);
            }

            var waterCol = water.gameObject.AddComponent<TilemapCollider2D>();
            waterCol.usedByComposite = false;

            // merged box colliders for solid + water cells (per row run)
            var solidSet = new HashSet<Vector2Int>();
            foreach (var c in map.solid) solidSet.Add(new Vector2Int(c.x, c.y));
            foreach (var c in map.waterCells) solidSet.Add(new Vector2Int(c.x, c.y));
            var colGo = new GameObject("Colliders");
            foreach (var run in MergeRuns(solidSet))
            {
                var bc = colGo.AddComponent<BoxCollider2D>();
                bc.offset = new Vector2(run.x + run.w / 2f, run.y + 0.5f);
                bc.size = new Vector2(run.w, 1f);
            }

            // objects
            foreach (var o in map.objects)
            {
                if (!string.IsNullOrEmpty(o.prefab))
                {
                    var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(o.prefab);
                    if (!prefab) { Debug.LogWarning("missing prefab: " + o.prefab); continue; }
                    var inst = (GameObject)PrefabUtility.InstantiatePrefab(prefab, scene);
                    inst.transform.position = new Vector3(o.x, o.y, 0f);
                    foreach (var sr in inst.GetComponentsInChildren<SpriteRenderer>())
                        sr.sortingOrder = Mathf.RoundToInt(-o.y * 10f) + 100;
                    if (o.kind == "chest")
                    {
                        var cg = inst.AddComponent<ChestGold>();
                        cg.gold = o.gold;
                        var bc = inst.AddComponent<BoxCollider2D>();
                        bc.size = Vector2.one;
                    }
                    else if (o.kind == "crop")
                    {
                        var ssf = inst.GetComponentInChildren<SuperRetroMainBundle.SpriteSelectFrame>();
                        if (ssf) ssf.spriteIndex = o.stage;
                    }
                }
                else if (!string.IsNullOrEmpty(o.type))
                {
                    var go = new GameObject($"{o.type}_{o.npcName}");
                    go.transform.position = new Vector3(o.x, o.y + 0.5f, 0f);
                    var sr = go.AddComponent<SpriteRenderer>();
                    sr.sortingOrder = Mathf.RoundToInt(-o.y * 10f) + 100;
                    var anim = go.AddComponent<SheetAnimator>();
                    anim.sheet = o.sheet;
                    anim.layout = o.type == "pig" ? SheetAnimator.Layout.Dirs : SheetAnimator.Layout.Grid;
                    anim.fps = o.type == "pig" ? 6f : 4f;
                    var bc = go.AddComponent<BoxCollider2D>();
                    bc.size = new Vector2(0.7f, 0.6f);
                    if (o.type == "npc")
                    {
                        var n = go.AddComponent<NpcDialog>();
                        n.npcName = o.npcName; n.line = o.line;
                    }
                    else
                    {
                        var w = go.AddComponent<WanderAnimal>();
                        w.petName = string.IsNullOrEmpty(o.npcName) ? o.type : o.npcName;
                        w.radius = o.type == "pig" ? 3f : 2f;
                    }
                }
            }

            // crop plots on tilled cells
            var plotsGo = new GameObject("CropPlots");
            foreach (var t in map.tilled)
            {
                var go = new GameObject($"plot_{t.x}_{t.y}");
                go.transform.SetParent(plotsGo.transform, false);
                go.transform.position = new Vector3(t.x + 0.5f, t.y + 0.5f, 0f);
                var bc = go.AddComponent<BoxCollider2D>();
                bc.isTrigger = true;
                bc.size = Vector2.one;
                go.AddComponent<CropPlot>();
            }

            // player + interactor
            var playerPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(map.player.prefab);
            var player = (GameObject)PrefabUtility.InstantiatePrefab(playerPrefab, scene);
            player.transform.position = new Vector3(map.player.x, map.player.y, 0f);
            player.tag = "Player";
            if (!player.GetComponent<Interactor>()) player.AddComponent<Interactor>();

            // manager + night overlay
            var mgr = new GameObject("FarmSliceManager");
            mgr.AddComponent<FarmSliceManager>();
            mgr.AddComponent<NightOverlay>();

            EditorSceneManager.SaveScene(scene, ScenePath);
            Debug.Log($"FarmSlice scene built -> {ScenePath} ({map.objects.Length} objects)");
        }

        static void Fill(Tilemap tm, CellEntry[] cells, Dictionary<string, TileBase> mats)
        {
            foreach (var c in cells)
                if (mats.TryGetValue(c.m, out var tile) && tile)
                    tm.SetTile(new Vector3Int(c.x, c.y, 0), tile);
        }

        struct Run { public int x, y, w; }
        static List<Run> MergeRuns(HashSet<Vector2Int> cells)
        {
            var runs = new List<Run>();
            var used = new HashSet<Vector2Int>();
            foreach (var c in cells)
            {
                if (used.Contains(c)) continue;
                int w = 0;
                while (cells.Contains(new Vector2Int(c.x + w, c.y))) w++;
                for (int i = 0; i < w; i++) used.Add(new Vector2Int(c.x + i, c.y));
                runs.Add(new Run { x = c.x, y = c.y, w = w });
            }
            return runs;
        }

        // ------------- JsonUtility data classes -------------
        [System.Serializable] public class MatEntry { public string key, path; }
        [System.Serializable] public class CellEntry { public int x, y; public string m; }
        [System.Serializable] public class XY { public int x, y; }
        [System.Serializable] public class ObjEntry
        {
            public string prefab, type, sheet, kind, npcName, line;
            public float x, y;
            public int gold, stage;
            public bool wander, light;
        }
        [System.Serializable] public class PlayerEntry { public string prefab; public float x, y; }
        [System.Serializable] public class MapData
        {
            public int W, H;
            public MatEntry[] materials;
            public CellEntry[] ground, soil, path, water, decor;
            public ObjEntry[] objects;
            public PlayerEntry player;
            public XY[] solid, waterCells, tilled, tillableBeds;
        }
    }
}
